dist: xenial

language: go

go:
  - 1.12.x

git:
  depth: 1

before_script:
  # install golangci-lint
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0

script:
  - golangci-lint run
  - go test -v -race ./...
