dist: bionic

language: go

go:
  - 1.13.x

git:
  depth: 1

install: true

before_script:
  # install golangci-lint
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0

script:
  - golangci-lint run
  - go test -v -race ./...
