build: off

clone_folder: c:\gopath\src\github.com\gky360\atsrv
clone_depth: 1

environment:
  GOPATH: c:\gopath

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;C:\msys64\mingw64\bin;%PATH%
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - gcc --version

stack: go 1.13

test_script:
  - go test -v -race ./...
